---
- name: Management Entry DNS
  #  hosts: [DNS-Master]
  hosts: localhost
  gather_facts: yes
  become: true
  become_method: sudo

  vars_files:
 #   - vars/main.yml
    - vars.yml

  tasks:



            - lineinfile:
                    #  dest: /etc/ansible/ansible.cfg
                  dest: /etc/bind/named.conf.options.back
                  line: '#inventory = /home/ubuntu/inventoryini'
                  # insertafter: '\[defaults\]'
                  insertafter: 'acl \"trusted\" \{'

            - lineinfile:
                  dest: /etc/bind/zones/db.12.48.back
                  line: '{{REVERS}}     IN      PTR     {{NAME}}.{{FQDN}}.  ; {{PRIVAT_IP}}'
                  insertafter: '\; PTR Records'


            - lineinfile:
                  dest: /etc/bind/zones/db.test1.energismesand.com.back
                  line: '{{NAME}}.{{FQDN}}.          IN      A       {{PRIVAT_IP}}'
                  insertafter: '\; 12.48.0.0/19 - A record'



            - lineinfile:
                  dest: /etc/bind/named.conf.options.back
                  line: '        {{PRIVAT_IP}};  #{{HOSTNAME}}:'
                  insertafter: 'acl \"trusted\" \{'


            - lineinfile:
                  dest: /etc/bind/named.conf.options.back
                  line: '        {{PRIVAT_IP}};  #{{HOSTNAME}}:'
                  insertafter: 'acl \"trusted\" \{'